version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_KIBANA_URL=http://localhost:5601
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    command: npm start
    stdin_open: true
    tty: true

  api:
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  monitor:
    volumes:
      - ./monitor:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
